// Make rest requests to API
// Requires REST Client from marketplace

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ5OTU4MzIyLCJleHAiOjE2NDk5NTgzODJ9.eYrJFiwTV10NttMSbKL7RXqGi76I6JuqCEEBLHERfCM"
}

###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ5OTU4MzIyLCJleHAiOjE2NDk5NTgzODJ9.eYrJFiwTV10NttMSbKL7RXqGi76I6JuqCEEBLHERfCM


# GET http://localhost:4000/posts
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjQ4MDI2MzU5fQ.1XVczEJqHd5by4o7mXcveza4A_YoUxUbni9wo-p5EQE

###
GET http://localhost:4000/users


###
POST http://localhost:4000/users
Content-Type: application/json

{
  "name": "Jim",
  "password": "password"
}

###
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "name": "Jim",
  "password": "password"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwicGFzc3dvcmQiOiIkMmIkMTAkOGpKdXlaQTJMeHA1NGdYd1pubUREdWVjUmQzRmZMWWtzaTNmSUJtbnU4SmpNZWgyZ013VkMiLCJpYXQiOjE2NDgwMzU1Njd9.v6hePEP2r3ePM9_P_5-XyKde7LAQ5xTj9gP8cYt2r-s"
}

# POST http://localhost:3000/users/login
# Content-Type: application/json

# {
#   "name": "Kyle"
# }
